### ISSUE TITLE
Wrong music thumbnail

### ISSUE THREAD

**Issue by RedHeadEmile** [deckerth/FoobarRemoteController2#2]
Hi, on the app, the wrong thumbnail is shown on the songs. And when the right is shown, it won't update when playing the next song.
![image](https://github.com/user-attachments/assets/ea3f7f90-b2e0-4078-beb9-ad2a0bc4836b)
![image](https://github.com/user-attachments/assets/8a3c5223-4985-48f6-96b4-6de33e27e30c)

Also, could it be possible to change the volume from the App ?

I saw that you are working on other branches here, is it possible to contribute ? Is there already a TODO-list of things to do ?

Thanks :)

**Comment by deckerth** [comment]
Hi, we are working on a completely new version of the App. It is will come
without the various shortcomings of the current version. It will completely
integrate into Android capabilities including Volume control. We are also
adding a configurable layout option. So, stay tuned. We aim of publishing
it this year.

RedHeadEmile ***@***.***> schrieb am Fr., 1. Nov. 2024, 18:41:

**Comment by deckerth** [comment]
As soon as we have pur new App running, we will discuss opening the repo for contributors.

**Comment by deckerth** [comment]
Check out the discussion on this topic: https://github.com/deckerth/FoobarRemoteController2/discussions/1#discussioncomment-11142826
